/*
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("https://www.zippyjot.com/");
    driver.manage().window().setSize(new Dimension(1512, 870));
    driver.findElement(By.cssSelector(".ui-widget-content")).click();
    driver.findElement(By.name("notetitle")).click();
    driver.findElement(By.name("notetitle")).sendKeys("заметка");
    driver.findElement(By.id("textarea")).click();
    driver.findElement(By.id("textarea")).sendKeys("очень классный текст");
    driver.findElement(By.cssSelector(".ui-button-text")).click();
    js.executeScript("window.scrollTo(0,558.5)");
    driver.findElement(By.linkText("Edit Note")).click();
    driver.findElement(By.id("textarea")).click();
    js.executeScript("window.scrollTo(0,281)");
    driver.findElement(By.id("textarea")).sendKeys("очень классный текст теперь изменился");
    driver.findElement(By.cssSelector(".ui-button-text")).click();
    js.executeScript("window.scrollTo(0,199.5)");
    driver.findElement(By.linkText("Delete Note")).click();
    assertThat(driver.switchTo().alert().getText(), is("Do you really want to Delete this note?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.linkText("Sign Out")).click();
    driver.close();
  }
}
*/
